version: '3.9'

services:
  db:
    container_name: dataset
    build:
      dockerfile: ./Dockerfile
    ports:
      - '1433:1433'

# services:
#   db:
#     image: mcr.microsoft.com/mssql/server:2017-latest
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d
#     environment:
#         SA_PASSWORD: "Password1234"
#         ACCEPT_EULA: "Y"
#     ports:
#       - '1433:1433'
